---
# Fail if distro is not supported (currenyly only CentOS)
- name: Fail if distro not supported
  fail:
    msg: "Distro '{{ ansible_os_family }}' not supported, exiting now!"
  when: ansible_os_family not in ['CentOS', 'RedHat']

# Load variables
- name: Load variables
  include_vars: "{{ ansible_distribution }}.yml"
  
# Install Pgpool-II
- name: Install PgPool-II
  import_tasks: install.yml
  tags:
    - install

# Configure Pgpool-II
- name: Configure PgPool-II
  import_tasks: configure.yml
  tags:
    - configure

# Copy command files
- name: Copy command files
  import_tasks: commands.yml
  tags:
    - commands

# Setup logs
- name: Setup logs
  import_tasks: log.yml
  tags:
    - log
  when: pgpool2_log_destination == 'syslog'

# Finalize installation (SSH keys, sudoers, etc.)
- name: Finalize installation (SSH keys, sudoers, etc.)
  import_tasks: finalize.yml
  tags:
    - finalize
